services:
  redis:
    image: redis:alpine  
    container_name: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-server_data:/data/server
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - .env
    networks:
      - backend
  
  app:
    build: .
    image: 'arnabpal342002/code_review_webhook'
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
    - redis
    networks:
      - backend

  migrate:
    image: 'arnabpal342002/code_review_webhook'
    container_name: db_migration
    env_file:
      - .env
    command: ["npm", "run", "db:deploy"]
    networks:
      - backend

volumes:
  redis-server_data:

networks:
  backend:
    driver: bridge