services:
  redis:
    image: redis:alpine  
    container_name: redis-server
    ports:
      - 6378:6378
    volumes:
      - redis-code-review-server_data:/data/server
    command: ["redis-server", "--port", "6378", "--appendonly", "yes"]
    env_file:
      - .env
    networks:
      - backend
  
  app:
    # build: .
    image: 'arnabpal342002/code_review_webhook'
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend

  migrate:
    build: .
    container_name: db_migration
    env_file:
      - .env
    command: ["npm", "run", "db:deploy"]
    networks:
      - backend

volumes:
  redis-code-review-server_data:

networks:
  backend:
    driver: bridge